# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: usersapi
      POSTGRES_PASSWORD: usersapi

volumes:
  db:
