version: "3"

services:
    eureka:
        container_name: eureka_server
        build:
            context: ./eureka-server
            dockerfile: Dockerfile
        restart: always
        networks:
            - backend
        ports:
            - '8761:8761'       
    administrator:
        container_name: administrator
        build:
            context: ./administrator-api
            dockerfile: Dockerfile
        networks:
            - backend
        ports:
            - '8085:8085'
    liquibase:
        container_name: liquibase
        image: liquibase/liquibase
        command: --url=jdbc:postgresql://users-db:5432/users?user=postgres&password=postgres --changeLogFile=changelog.xml update
        volumes:
            - ./users-api-webflux/src/main/resources/db/changelog/changelog-master.xml:/liquibase/changelog.xml
            - ./users-api-webflux/src/main/resources/db/changelog/changes:/liquibase/scripts
        networks:
            - backend
        depends_on:
            - users-db
    users-db:
        container_name: users-db
        image: postgres
        restart: always
        environment:
            POSTGRES_DB: users
    users-api:
        container_name: users-api

networks:
    backend:
